dist: bionic
language: csharp
solution: Astron.sln
mono: none
dotnet: 2.2.203
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true
stages:
  - build
  - test
jobs:
  include:
    - stage: build
      name: build solution
      script: dotnet restore && dotnet build
    - stage: test
      name: run-tests
      script: ./run-tests.sh